version: "3.8"

services:
  homepage:
    build: .
    container_name: homepage-app
    ports:
      - "8001:8000"   # host:container
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
    networks:
      - homepage-network

networks:
  homepage-network:
    driver: bridge